# Meta
environment: "operations" # Name of the environment

# AWS
aws_account_id: "153248837753" # ID of the aws account to use for the aws provider
aws_profile: "corgeek-operations-superuser" # Name of the AWS CLI profile to use for the aws provider
aws_secondary_account_id: "153248837753" #ID of the aws account to use for the aws_secondary provider
aws_secondary_profile: "corgeek-operations-superuser" # Name of the AWS CLI profile to use for the aws_secondary provider

# State Bucket
tf_state_account_id: "153248837753" # AWS Account for the S3 bucket holding the state file
tf_state_region: "us-west-2" # Region for the S3 bucket holding the state file
tf_state_bucket: "corgeek-tf-state-operations" # S3 bucket holding the state file
tf_state_lock_table: "corgeek-tf-locks-operations" # Dynamodb table holding state locks"
tf_state_profile: "corgeek-operations-superuser" # AWS profile to assume for working with the state files
